version: "3.9"

services:

  postgres:
    image: brackets_postgres
    networks: 
      - net1
    volumes:
      - "brackets_postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: keycl0ak
      POSTGRES_USER: keycl0ak
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_IMPORT: /keycloak/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycl0ak
      DB_USER: keycl0ak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
    networks: 
      net1:
         aliases:
           - keycloak.mydomain.com
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./keycloak:/keycloak_realm
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/keycloak_realm/realm-export.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"

  web:
    image: brackets_fe
    networks: 
      net1:
        aliases:
          - brackets.mydomain.com
    ports:
      - "3001:80"
    environment:
      - NGINX_HOST=brackets.mydomain.com
      - NGINX_PORT=80
    depends_on:
      - server
      - keycloak

  server:
    image: brackets_be
    networks:
      - net1
    depends_on:
      - postgres
      - keycloak
    environment:
      KEYCLOAK_IMPORT: /keycloak/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      BRACKETS_DB_HOST: postgres
      POSTGRES_USER: keycl0ak
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"


volumes:
  brackets_postgres:
networks:
  net1:
    external: true
    name: bracket_net

